/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Random;

public class App {

    static void imprimi_tabuleiro(String[][] tab){

        for(int i = 0; i < 10; i++){

            for(int j = 0; j < 10; j++){

                System.out.printf(tab[i][j]);

            }
            
            System.out.printf("\n");
        }

    }

    static String retorna_simbolo(int num){

        // Ver tabela comentada no método monta_tabuleiro
        switch(num){

            case 5  :   return "P ";
            case 4  :   return "E ";
            case 3  :   return "C ";
            case 2  :   return "S ";
            case 1  :   return "N ";
            default :   return ". ";

        }

    }

    static String[][] monta_tabuleiro(String[][] tabuleiro){

        /*
         *    Navio         Tamanho (casas)    Símbolo
         * Porta-Aviões         5                P
         * Encouraçado          4                E
         * Cruzador             3                C
         * Submarino            3                S
         * Contratorpedeiro     2                N 
        */ 

        Random rand = new Random();
        String[][] tab = tabuleiro;

        //Porta-aviões
        int l = rand.nextInt(10); //guarda linha
        for(int k = 0; k < 5; k++){

            tab[l][k] = retorna_simbolo(5);

        }

        // Encouraçado
        l = rand.nextInt(10); //guarda linha
        for(int k = 0; k < 4; k ++){

            tab[l][k] = retorna_simbolo(4);

        }

        // Cruzador
        l = rand.nextInt(10); //guarda linha
        for(int k = 0; k < 3; k ++){

            tab[l][k] = retorna_simbolo(3);

        }

        // Submarino
        l = rand.nextInt(10); //guarda linha
        for(int k = 0; k < 3; k++){

            tab[l][k] = retorna_simbolo(2);

        }

        // Contratorpedeiro
        l = rand.nextInt(10); //guarda linha
        for(int k = 0; k < 2; k++){

            tab[l][k] = retorna_simbolo(1);

        }

        return tab;

    }

    public static void main(String[] args) {

        String[][] tabuleiro = new String[10][10];

        for(int i = 0; i < 10; i++){

            for(int j = 0; j < 10; j++){

                tabuleiro[i][j] = ". ";

            }

        }

        tabuleiro = monta_tabuleiro(tabuleiro);
        imprimi_tabuleiro(tabuleiro);
    }
}
