/*
 * This source file was generated by the Gradle 'init' task
 * Desenvolvido por Igor da Silva
 */
package org.example;
import java.util.Random;

public class App {

    static void imprimir_tabuleiro(String[][] tab){

        for(int i = 0; i < 10; i++){

            for(int j = 0; j < 10; j++)
                System.out.printf(tab[i][j]);            
            
            System.out.printf("\n");
        }

    }

    static String retornar_simbolo(String navio){

        // Ver tabela comentada no método monta_tabuleiro
        // O switch retorna o símbolo do navio associado ao seu próprio nome
        return switch (navio) {
            case "porta-avioes"     -> "P ";
            case "encouracado"      -> "E ";
            case "cruzador"         -> "C ";
            case "submarino"        -> "S ";
            case "contratorpedeiro" -> "N ";
            default -> ". "; // Coloquei este default, pois caso contrário não compilava...
        };

    }

    // Retorna:
    //      1 se a faixa está livre
    //      0 caso contrário
    static int faixa_livre(String[][] tab, int linha, int coluna, int num, int hori_vert){

        // num é a quantidade de navios
        // hori_vert:
            // Se for 1, os navios serão posicionados na horizontal
            // Se for 0, os navios serão posicionados na vertical

        if(hori_vert == 1){ // Aqui eu vou verificar se posso posicionar na horizontal

            if(coluna + num > 10)
                return 0; // ultrapassou o limite do tabuleiro (observação do professor)

            // Vou verificar se tem alguma posição ocupada: se a posição for diferente
            // de ". ", significa que tem um navio nessa posição...

            for(int i = coluna; i < coluna + num; i++){

                if(! tab[linha][i].equals(". "))
                    return 0;

            }

        } 
        else {

            if(linha + num > 10)
                return 0; // Ultrpassou o limite do tabuleiro (observação do professor)

            // Vou verificar se tem alguma posição ocupada (mesmo procedimento que no if acima)    
            for(int i = linha; i < linha + num; i++)
                if(! tab[i][coluna].equals(". "))
                    return 0;

        }

        return 1;

    }

    // Função responsável por posicionar uma faixa de navios genéricos
    // na horizontal ou vertical
    static void posicionar_navio(String [][] tab, int num, String navio){

        // num é a quantidade de navios
        Random aleatorio = new Random();
        int foi_posicionado = 0; // Uma flag para marcar se uma faixa de navio foi posicionada

        while(foi_posicionado == 0) {

            int linha_inicial = aleatorio.nextInt(10);
            int coluna_inicial = aleatorio.nextInt(10);
            int hori_vert = aleatorio.nextInt(2); // 1 é horizontal e 0 é vertical

            if(faixa_livre(tab, linha_inicial, coluna_inicial, num, hori_vert) == 1){

                // Se a faixa (h ou v) está livre, vamos posicionar os navios
                for(int i = 0; i < num; i++){

                    if(hori_vert == 1)
                        tab[linha_inicial][coluna_inicial + i] = retornar_simbolo(navio);
                    else     
                        tab[linha_inicial + i][coluna_inicial] = retornar_simbolo(navio);
                }

                foi_posicionado = 1;
            }

        }

    }

    // Apenas chama a função posicionar_navios para
    // distribuir cada quantidade de navios pelo tabuleiro
    static String[][] montar_tabuleiro(String[][] tab){

        /*          TABELA DE NAVIOS
         *    Navio         Tamanho (casas)    Símbolo
         * Porta-Aviões         5                P
         * Encouraçado          4                E
         * Cruzador             3                C
         * Submarino            3                S
         * Contratorpedeiro     2                N 
        */ 

        posicionar_navio(tab, 5, "porta-avioes");
        posicionar_navio(tab, 4, "encouracado");
        posicionar_navio(tab, 3, "cruzador");
        posicionar_navio(tab, 3, "submarino");
        posicionar_navio(tab, 2, "contratorpedeiro");

        return tab;
    }

    public static void main(String[] args) {

        String[][] tabuleiro = new String[10][10];

        // Vou setar o tabuleiro todo com ". "
        for(int i = 0; i < 10; i++)
            for(int j = 0; j < 10; j++)
                tabuleiro[i][j] = ". ";     

        tabuleiro = montar_tabuleiro(tabuleiro);
        imprimir_tabuleiro(tabuleiro);
    }
}